export const hotelData = [
  {
    id: 1,
    title: "Luxury Room, 1 King Bed",
    rating: 9.2,
    ratingText: "Wonderful",
    reviews: 197,
    sleeps: 4,
    bedType: "1 King Bed",
    refundPolicy: "Fully refundable",
    refundDate: "Before Sun, Dec 15",
    priceDetails: {
      discount: "$42 off",
      currentPrice: "$170",
      originalPrice: "$212",
      totalPrice: "$249",
      includes: "includes taxes & fees",
    },
    reservationNote: "You will not be charged yet",
    images: ["/h1.jpg", "/h2.jpg", "/h3.jpg"],
    additionalDetails: {
      description: "Luxury Room, 1 King Bed, City View",
      highlights: [
        "Separate sitting area",
        "Air conditioning",
        "Free cribs/infant beds",
        "HDTV",
        "Hypo-allergenic bedding",
        "Blackout drapes/curtains",
        "Pillowtop bed",
        "Down duvet",
      ],
      view: "City view",
      bathroom: [
        "Free toiletries",
        "Hair dryer",
        "Private bathroom",
        "Shampoo",
        "Slippers",
        "Soap",
        "Toilet paper",
        "Towels",
        "Blackout drapes/curtains",
        "Climate-controlled air conditioning",
        "Down duvet",
      ],
      bedroom: [
        "Bed sheets",
        "Blackout drapes/curtains",
        "Climate-controlled air conditioning",
        "Down duvet",
        "Egyptian cotton linens",
        "Free cribs/infant beds",
        "Hypo-allergenic bedding",
        "Pillowtop bed",
        "Premium bedding",
        "Sofa bed - double",
      ],
      entertainment: [
        "46-inch HDTV",
        "Pay movies",
        "Premium TV channels",
      ],
      foodAndDrink: [
        "24-hour room service",
        "Champagne service",
        "Minibar (fees may apply)",
      ],
      internet: "WiFi",
      more: [
        "Daily housekeeping",
        "Desk",
        "Desk chair",
        "Free local calls",
        "Iron/ironing board",
        "Laptop workspace",
        "LED light bulbs",
        "Phone",
        "Recycling bin",
        "Safe",
        "Sitting area",
        "Wardrobe or closet",
      ],
      accessibility: [
        "Braille signage",
        "Closed-captioned TV",
        "Doorbell and phone notification",
        "Lever door handles",
        "Visual fire alarm",
      ],
      amenities: [
        "Bathrobes",
        "Deep soaking bathtub",
        "Eco-friendly toiletries",
      ],
      guestLikes: [
        "Nice bed (55 reviews)",
        "Quiet (33 reviews)",
        "Clean bathroom (33 reviews)",
        "Spacious (67 reviews)",
        "Renovated, new (5 reviews)",
        "Clean (62 reviews)",
        "Great amenities (30 reviews)",
      ],
      ratingDetails: {
        overallRating: 9.4,
        reviews: 108,
        reviewText: "Exceptional",
        guestLikes: [
          "Nice bed (55 reviews)",
          "Quiet (33 reviews)",
          "Clean bathroom (33 reviews)",
          "Spacious (67 reviews)",
          "Renovated, new (5 reviews)",
          "Clean (62 reviews)",
          "Great amenities (30 reviews)",
        ],
      },
    },
  },
  {
    id: 2,
    title: "Premium Suite, 2 Queen Beds",
    rating: 8.7,
    ratingText: "Very Good",
    reviews: 120,
    sleeps: 6,
    bedType: "2 Queen Beds",
    refundPolicy: "Fully refundable",
    refundDate: "Before Thu, Dec 20",
    priceDetails: {
      discount: "$30 off",
      currentPrice: "$220",
      originalPrice: "$250",
      totalPrice: "$280",
      includes: "includes taxes & fees",
    },
    reservationNote: "You will not be charged yet",
    images: ["/ca9.jpg", "/ca8.jpg", "/ca7.jpg"],
    additionalDetails: {
      description: "Premium Suite, 2 Queen Beds, Ocean View",
      highlights: [
        "Private balcony",
        "Air conditioning",
        "Free cribs/infant beds",
        "HDTV",
        "Hypo-allergenic bedding",
        "Blackout drapes/curtains",
        "Pillowtop bed",
        "Down duvet",
      ],
      view: "Ocean view",
      bathroom: [
        "Free toiletries",
        "Hair dryer",
        "Private bathroom",
        "Shampoo",
        "Slippers",
        "Soap",
        "Toilet paper",
        "Towels",
        "Climate-controlled air conditioning",
        "Down duvet",
      ],
      bedroom: [
        "Bed sheets",
        "Blackout drapes/curtains",
        "Climate-controlled air conditioning",
        "Down duvet",
        "Egyptian cotton linens",
        "Free cribs/infant beds",
        "Hypo-allergenic bedding",
        "Pillowtop bed",
        "Premium bedding",
        "Sofa bed - double",
      ],
      entertainment: [
        "46-inch HDTV",
        "Premium TV channels",
      ],
      foodAndDrink: [
        "Minibar (fees may apply)",
        "Coffee/tea maker",
      ],
      internet: "WiFi",
      more: [
        "Daily housekeeping",
        "Iron/ironing board",
        "Laptop workspace",
        "LED light bulbs",
        "Phone",
        "Recycling bin",
        "Safe",
        "Sitting area",
        "Wardrobe or closet",
      ],
      accessibility: [
        "Braille signage",
        "Closed-captioned TV",
        "Lever door handles",
        "Visual fire alarm",
      ],
      amenities: [
        "Bathrobes",
        "Deep soaking bathtub",
        "Eco-friendly toiletries",
      ],
      guestLikes: [
        "Clean (50 reviews)",
        "Quiet (30 reviews)",
        "Spacious (40 reviews)",
        "Great amenities (25 reviews)",
      ],
      ratingDetails: {
        overallRating: 9.0,
        reviews: 80,
        reviewText: "Great",
        guestLikes: [
          "Nice bed (40 reviews)",
          "Quiet (20 reviews)",
          "Spacious (35 reviews)",
        ],
      },
    },
  },
  {
    id: 3,
    title: "Standard Room, 1 Queen Bed",
    rating: 8.0,
    ratingText: "Good",
    reviews: 55,
    sleeps: 2,
    bedType: "1 Queen Bed",
    refundPolicy: "Fully refundable",
    refundDate: "Before Wed, Dec 10",
    priceDetails: {
      discount: "$10 off",
      currentPrice: "$100",
      originalPrice: "$110",
      totalPrice: "$120",
      includes: "includes taxes & fees",
    },
    reservationNote: "You will not be charged yet",
    images: ["/h8.jpg", "/h9.jpg", "/ca1.jpg"],
    additionalDetails: {
      description: "Standard Room, 1 Queen Bed, Garden View",
      highlights: [
        "Free cribs/infant beds",
        "Air conditioning",
        "HDTV",
        "Blackout drapes/curtains",
        "Pillowtop bed",
      ],
      view: "Garden view",
      bathroom: [
        "Free toiletries",
        "Hair dryer",
        "Private bathroom",
        "Shampoo",
        "Soap",
        "Towels",
      ],
      bedroom: [
        "Bed sheets",
        "Pillowtop bed",
        "Premium bedding",
      ],
      entertainment: [
        "46-inch HDTV",
        "Premium TV channels",
      ],
      foodAndDrink: [
        "Minibar (fees may apply)",
      ],
      internet: "WiFi",
      more: [
        "Daily housekeeping",
        "Desk",
        "Iron/ironing board",
        "Phone",
        "Recycling bin",
        "Wardrobe or closet",
      ],
      accessibility: [
        "Braille signage",
        "Closed-captioned TV",
      ],
      amenities: [
        "Bathrobes",
      ],
      guestLikes: [
        "Clean (40 reviews)",
        "Comfortable (20 reviews)",
      ],
      ratingDetails: {
        overallRating: 8.0,
        reviews: 50,
        reviewText: "Good",
        guestLikes: [
          "Clean (30 reviews)",
          "Comfortable (15 reviews)",
        ],
      },
    },
  },
  {
    id: 4,
    title: "Deluxe Suite, 1 King Bed",
    rating: 9.5,
    ratingText: "Exceptional",
    reviews: 340,
    sleeps: 4,
    bedType: "1 King Bed",
    refundPolicy: "Fully refundable",
    refundDate: "Before Fri, Dec 25",
    priceDetails: {
      discount: "$50 off",
      currentPrice: "$300",
      originalPrice: "$350",
      totalPrice: "$380",
      includes: "includes taxes & fees",
    },
    reservationNote: "You will not be charged yet",
    images: ["/h4.jpg", "/h5.jpg", "/h6.jpg"],
    additionalDetails: {
      description: "Deluxe Suite, 1 King Bed, Sea View",
      highlights: [
        "Private balcony",
        "Air conditioning",
        "HDTV",
        "Hypo-allergenic bedding",
        "Pillowtop bed",
        "Free cribs/infant beds",
      ],
      view: "Sea view",
      bathroom: [
        "Free toiletries",
        "Hair dryer",
        "Private bathroom",
        "Shampoo",
        "Slippers",
        "Soap",
        "Toilet paper",
        "Towels",
      ],
      bedroom: [
        "Bed sheets",
        "Pillowtop bed",
        "Premium bedding",
        "Egyptian cotton linens",
      ],
      entertainment: [
        "48-inch HDTV",
        "Premium TV channels",
      ],
      foodAndDrink: [
        "Minibar (fees may apply)",
        "Coffee maker",
      ],
      internet: "WiFi",
      more: [
        "Daily housekeeping",
        "Iron/ironing board",
        "Phone",
        "Laptop workspace",
        "Safe",
        "Sitting area",
        "Wardrobe or closet",
      ],
      accessibility: [
        "Braille signage",
        "Closed-captioned TV",
        "Lever door handles",
      ],
      amenities: [
        "Bathrobes",
        "Deep soaking bathtub",
        "Eco-friendly toiletries",
      ],
      guestLikes: [
        "Great view (60 reviews)",
        "Spacious (40 reviews)",
        "Clean (50 reviews)",
      ],
      ratingDetails: {
        overallRating: 9.5,
        reviews: 100,
        reviewText: "Exceptional",
        guestLikes: [
          "Great view (60 reviews)",
          "Spacious (40 reviews)",
        ],
      },
    },
  },
  {
    id: 5,
    title: "Luxury Room, 1 King Bed",
    rating: 9.2,
    ratingText: "Wonderful",
    reviews: 197,
    sleeps: 4,
    bedType: "1 King Bed",
    refundPolicy: "Fully refundable",
    refundDate: "Before Sun, Dec 15",
    priceDetails: {
      discount: "$42 off",
      currentPrice: "$170",
      originalPrice: "$212",
      totalPrice: "$249",
      includes: "includes taxes & fees",
    },
    reservationNote: "You will not be charged yet",
    images: ["/h1.jpg", "/h2.jpg", "/h3.jpg"],
    additionalDetails: {
      description: "Luxury Room, 1 King Bed, City View",
      highlights: [
        "Separate sitting area",
        "Air conditioning",
        "Free cribs/infant beds",
        "HDTV",
        "Hypo-allergenic bedding",
        "Blackout drapes/curtains",
        "Pillowtop bed",
        "Down duvet",
      ],
      view: "City view",
      bathroom: [
        "Free toiletries",
        "Hair dryer",
        "Private bathroom",
        "Shampoo",
        "Slippers",
        "Soap",
        "Toilet paper",
        "Towels",
        "Blackout drapes/curtains",
        "Climate-controlled air conditioning",
        "Down duvet",
      ],
      bedroom: [
        "Bed sheets",
        "Blackout drapes/curtains",
        "Climate-controlled air conditioning",
        "Down duvet",
        "Egyptian cotton linens",
        "Free cribs/infant beds",
        "Hypo-allergenic bedding",
        "Pillowtop bed",
        "Premium bedding",
        "Sofa bed - double",
      ],
      entertainment: [
        "46-inch HDTV",
        "Pay movies",
        "Premium TV channels",
      ],
      foodAndDrink: [
        "24-hour room service",
        "Champagne service",
        "Minibar (fees may apply)",
      ],
      internet: "WiFi",
      more: [
        "Daily housekeeping",
        "Desk",
        "Desk chair",
        "Free local calls",
        "Iron/ironing board",
        "Laptop workspace",
        "LED light bulbs",
        "Phone",
        "Recycling bin",
        "Safe",
        "Sitting area",
        "Wardrobe or closet",
      ],
      accessibility: [
        "Braille signage",
        "Closed-captioned TV",
        "Doorbell and phone notification",
        "Lever door handles",
        "Visual fire alarm",
      ],
      amenities: [
        "Bathrobes",
        "Deep soaking bathtub",
        "Eco-friendly toiletries",
      ],
      guestLikes: [
        "Nice bed (55 reviews)",
        "Quiet (33 reviews)",
        "Clean bathroom (33 reviews)",
        "Spacious (67 reviews)",
        "Renovated, new (5 reviews)",
        "Clean (62 reviews)",
        "Great amenities (30 reviews)",
      ],
      ratingDetails: {
        overallRating: 9.4,
        reviews: 108,
        reviewText: "Exceptional",
        guestLikes: [
          "Nice bed (55 reviews)",
          "Quiet (33 reviews)",
          "Clean bathroom (33 reviews)",
          "Spacious (67 reviews)",
          "Renovated, new (5 reviews)",
          "Clean (62 reviews)",
          "Great amenities (30 reviews)",
        ],
      },
    },
  },
  {
    id: 6,
    title: "Premium Suite, 2 Queen Beds",
    rating: 8.7,
    ratingText: "Very Good",
    reviews: 120,
    sleeps: 6,
    bedType: "2 Queen Beds",
    refundPolicy: "Fully refundable",
    refundDate: "Before Thu, Dec 20",
    priceDetails: {
      discount: "$30 off",
      currentPrice: "$220",
      originalPrice: "$250",
      totalPrice: "$280",
      includes: "includes taxes & fees",
    },
    reservationNote: "You will not be charged yet",
    images: ["/ca7.jpg", "/ca8.jpg", "/ca9.jpg"],
    additionalDetails: {
      description: "Premium Suite, 2 Queen Beds, Ocean View",
      highlights: [
        "Private balcony",
        "Air conditioning",
        "Free cribs/infant beds",
        "HDTV",
        "Hypo-allergenic bedding",
        "Blackout drapes/curtains",
        "Pillowtop bed",
        "Down duvet",
      ],
      view: "Ocean view",
      bathroom: [
        "Free toiletries",
        "Hair dryer",
        "Private bathroom",
        "Shampoo",
        "Slippers",
        "Soap",
        "Toilet paper",
        "Towels",
        "Climate-controlled air conditioning",
        "Down duvet",
      ],
      bedroom: [
        "Bed sheets",
        "Blackout drapes/curtains",
        "Climate-controlled air conditioning",
        "Down duvet",
        "Egyptian cotton linens",
        "Free cribs/infant beds",
        "Hypo-allergenic bedding",
        "Pillowtop bed",
        "Premium bedding",
        "Sofa bed - double",
      ],
      entertainment: [
        "46-inch HDTV",
        "Premium TV channels",
      ],
      foodAndDrink: [
        "Minibar (fees may apply)",
        "Coffee/tea maker",
      ],
      internet: "WiFi",
      more: [
        "Daily housekeeping",
        "Iron/ironing board",
        "Laptop workspace",
        "LED light bulbs",
        "Phone",
        "Recycling bin",
        "Safe",
        "Sitting area",
        "Wardrobe or closet",
      ],
      accessibility: [
        "Braille signage",
        "Closed-captioned TV",
        "Lever door handles",
        "Visual fire alarm",
      ],
      amenities: [
        "Bathrobes",
        "Deep soaking bathtub",
        "Eco-friendly toiletries",
      ],
      guestLikes: [
        "Clean (50 reviews)",
        "Quiet (30 reviews)",
        "Spacious (40 reviews)",
        "Great amenities (25 reviews)",
      ],
      ratingDetails: {
        overallRating: 9.0,
        reviews: 80,
        reviewText: "Great",
        guestLikes: [
          "Nice bed (40 reviews)",
          "Quiet (20 reviews)",
          "Spacious (35 reviews)",
        ],
      },
    },
  },
  {
    id: 7,
    title: "Standard Room, 1 Queen Bed",
    rating: 8.0,
    ratingText: "Good",
    reviews: 55,
    sleeps: 2,
    bedType: "1 Queen Bed",
    refundPolicy: "Fully refundable",
    refundDate: "Before Wed, Dec 10",
    priceDetails: {
      discount: "$10 off",
      currentPrice: "$100",
      originalPrice: "$110",
      totalPrice: "$120",
      includes: "includes taxes & fees",
    },
    reservationNote: "You will not be charged yet",
    images: ["/ca4.jpg", "/ca5.jpg", "/ca6.jpg"],
    additionalDetails: {
      description: "Standard Room, 1 Queen Bed, Garden View",
      highlights: [
        "Free cribs/infant beds",
        "Air conditioning",
        "HDTV",
        "Blackout drapes/curtains",
        "Pillowtop bed",
      ],
      view: "Garden view",
      bathroom: [
        "Free toiletries",
        "Hair dryer",
        "Private bathroom",
        "Shampoo",
        "Soap",
        "Towels",
      ],
      bedroom: [
        "Bed sheets",
        "Pillowtop bed",
        "Premium bedding",
      ],
      entertainment: [
        "46-inch HDTV",
        "Premium TV channels",
      ],
      foodAndDrink: [
        "Minibar (fees may apply)",
      ],
      internet: "WiFi",
      more: [
        "Daily housekeeping",
        "Desk",
        "Iron/ironing board",
        "Phone",
        "Recycling bin",
        "Wardrobe or closet",
      ],
      accessibility: [
        "Braille signage",
        "Closed-captioned TV",
      ],
      amenities: [
        "Bathrobes",
      ],
      guestLikes: [
        "Clean (40 reviews)",
        "Comfortable (20 reviews)",
      ],
      ratingDetails: {
        overallRating: 8.0,
        reviews: 50,
        reviewText: "Good",
        guestLikes: [
          "Clean (30 reviews)",
          "Comfortable (15 reviews)",
        ],
      },
    },
  },
  {
    id: 8,
    title: "Deluxe Suite, 1 King Bed",
    rating: 9.5,
    ratingText: "Exceptional",
    reviews: 340,
    sleeps: 4,
    bedType: "1 King Bed",
    refundPolicy: "Fully refundable",
    refundDate: "Before Fri, Dec 25",
    priceDetails: {
      discount: "$50 off",
      currentPrice: "$300",
      originalPrice: "$350",
      totalPrice: "$380",
      includes: "includes taxes & fees",
    },
    reservationNote: "You will not be charged yet",
    images: ["/ca1.jpg", "/ca2.jpg", "/ca3.jpg"],
    additionalDetails: {
      description: "Deluxe Suite, 1 King Bed, Sea View",
      highlights: [
        "Private balcony",
        "Air conditioning",
        "HDTV",
        "Hypo-allergenic bedding",
        "Pillowtop bed",
        "Free cribs/infant beds",
      ],
      view: "Sea view",
      bathroom: [
        "Free toiletries",
        "Hair dryer",
        "Private bathroom",
        "Shampoo",
        "Slippers",
        "Soap",
        "Toilet paper",
        "Towels",
      ],
      bedroom: [
        "Bed sheets",
        "Pillowtop bed",
        "Premium bedding",
        "Egyptian cotton linens",
      ],
      entertainment: [
        "48-inch HDTV",
        "Premium TV channels",
      ],
      foodAndDrink: [
        "Minibar (fees may apply)",
        "Coffee maker",
      ],
      internet: "WiFi",
      more: [
        "Daily housekeeping",
        "Iron/ironing board",
        "Phone",
        "Laptop workspace",
        "Safe",
        "Sitting area",
        "Wardrobe or closet",
      ],
      accessibility: [
        "Braille signage",
        "Closed-captioned TV",
        "Lever door handles",
      ],
      amenities: [
        "Bathrobes",
        "Deep soaking bathtub",
        "Eco-friendly toiletries",
      ],
      guestLikes: [
        "Great view (60 reviews)",
        "Spacious (40 reviews)",
        "Clean (50 reviews)",
      ],
      ratingDetails: {
        overallRating: 9.5,
        reviews: 100,
        reviewText: "Exceptional",
        guestLikes: [
          "Great view (60 reviews)",
          "Spacious (40 reviews)",
        ],
      },
    },
  },
  // // Add the same structure for other hotel entries...
  // {
  //   id: 2,
  //   title: "Deluxe Room, 2 Queen Beds",
  //   rating: 8.5,
  //   ratingText: "Very Good",
  //   reviews: 150,
  //   sleeps: 6,
  //   bedType: "2 Queen Beds",
  //   refundPolicy: "Fully refundable",
  //   refundDate: "Before Fri, Dec 20",
  //   priceDetails: {
  //     discount: "$30 off",
  //     currentPrice: "$180",
  //     originalPrice: "$210",
  //     totalPrice: "$240",
  //     includes: "includes taxes & fees",
  //   },
  //   reservationNote: "You will not be charged yet",
  //   images: ["/h4.jpg", "/h5.jpg", "/h6.jpg"],
  //   additionalDetails: {
  //     description: "Deluxe Room, 2 Queen Beds, City View",
  //     highlights: [
  //       "Separate sitting area",
  //       "Air conditioning",
  //       "Free cribs/infant beds",
  //       "HDTV",
  //       "Hypo-allergenic bedding",
  //       "Blackout drapes/curtains",
  //       "Pillowtop bed",
  //       "Down duvet",
  //     ],
  //     view: "City view",
  //     amenities: [
  //       "Free toiletries",
  //       "Hair dryer",
  //       "Private bathroom",
  //       "Shampoo",
  //       "Slippers",
  //       "Soap",
  //       "Toilet paper",
  //       "Towels",
  //       "Bed sheets",
  //       "Blackout drapes/curtains",
  //       "Climate-controlled air conditioning",
  //       "Down duvet",
  //       "Egyptian cotton linens",
  //       "Free cribs/infant beds",
  //       "Hypo-allergenic bedding",
  //       "Pillowtop bed",
  //       "Premium bedding",
  //       "Sofa bed - double",
  //     ],
  //     entertainment: [
  //       "46-inch HDTV",
  //       "Pay movies",
  //       "Premium TV channels",
  //     ],
  //     foodAndDrink: [
  //       "24-hour room service",
  //       "Champagne service",
  //       "Minibar (fees may apply)",
  //     ],
  //     internet: "WiFi",
  //     more: [
  //       "Daily housekeeping",
  //     ],
  //     accessibility: [
  //       "Braille signage",
  //       "Closed-captioned TV",
  //       "Doorbell and phone notification",
  //       "Lever door handles",
  //       "Visual fire alarm",
  //     ],
  //     bathroom: [
  //       "Bathrobes",
  //       "Deep soaking bathtub",
  //       "Eco-friendly toiletries",
  //     ],
  //     guestLikes: [
  //       "Nice bed (55 reviews)",
  //       "Quiet (33 reviews)",
  //       "Clean bathroom (33 reviews)",
  //       "Spacious (67 reviews)",
  //       "Renovated, new (5 reviews)",
  //       "Clean (62 reviews)",
  //       "Great amenities (30 reviews)",
  //     ],
  //     ratingDetails: {
  //       overallRating: 9.0,
  //       reviews: 120,
  //       reviewText: "Excellent",
  //       guestLikes: [
  //         "Nice bed (35 reviews)",
  //         "Quiet (30 reviews)",
  //         "Clean bathroom (20 reviews)",
  //         "Spacious (50 reviews)",
  //       ],
  //     },
  //   },
  // },

  // {
  //   id: 3,
  //   title: "Superior Suite, 1 King Bed",
  //   rating: 9.0,
  //   ratingText: "Excellent",
  //   reviews: 120,
  //   sleeps: 2,
  //   bedType: "1 King Bed",
  //   refundPolicy: "Fully refundable",
  //   refundDate: "Before Mon, Dec 18",
  //   priceDetails: {
  //     discount: "$50 off",
  //     currentPrice: "$220",
  //     originalPrice: "$270",
  //     totalPrice: "$290",
  //     includes: "includes taxes & fees",
  //   },
  //   reservationNote: "You will not be charged yet",
  //   images: ["/h7.jpg", "/h8.jpg", "/h9.jpg"],
  //   additionalDetails: {
  //     description: "Superior Suite, 1 King Bed, Ocean View",
  //     highlights: [
  //       "Private balcony",
  //       "Air conditioning",
  //       "Free Wi-Fi",
  //       "HDTV",
  //       "Memory foam mattress",
  //       "Refrigerator",
  //     ],
  //     view: "Ocean view",
  //     amenities: [
  //       "Free toiletries",
  //       "Hair dryer",
  //       "Private bathroom",
  //       "Shampoo",
  //       "Slippers",
  //       "Toilet paper",
  //       "Towels",
  //       "Bed sheets",
  //       "Blackout curtains",
  //     ],
  //     entertainment: [
  //       "50-inch HDTV",
  //       "Pay-per-view movies",
  //       "Premium TV channels",
  //     ],
  //     foodAndDrink: [
  //       "24-hour room service",
  //       "In-room dining",
  //       "Minibar",
  //     ],
  //     internet: "Wi-Fi",
  //     more: ["Daily housekeeping"],
  //     accessibility: [
  //       "Wheelchair accessible",
  //       "Visual fire alarm",
  //     ],
  //     bathroom: [
  //       "Deep soaking tub",
  //       "Bathrobes",
  //       "Eco-friendly toiletries",
  //     ],
  //     guestLikes: [
  //       "Nice bed (55 reviews)",
  //       "Quiet (33 reviews)",
  //       "Clean bathroom (33 reviews)",
  //       "Spacious (67 reviews)",
  //       "Renovated, new (5 reviews)",
  //       "Clean (62 reviews)",
  //       "Great amenities (30 reviews)",
  //     ],
  //     ratingDetails: {
  //       overallRating: 9.2,
  //       reviews: 95,
  //       reviewText: "Wonderful",
  //       guestLikes: [
  //         "Spectacular view (50 reviews)",
  //         "Spacious (30 reviews)",
  //         "Clean (15 reviews)",
  //       ],
  //     },
  //   },
  // },
  // {
  //   id: 4,
  //   title: "Standard Room, 2 Single Beds",
  //   rating: 8.0,
  //   ratingText: "Good",
  //   reviews: 180,
  //   sleeps: 4,
  //   bedType: "2 Single Beds",
  //   refundPolicy: "Fully refundable",
  //   refundDate: "Before Wed, Dec 25",
  //   priceDetails: {
  //     discount: "$20 off",
  //     currentPrice: "$130",
  //     originalPrice: "$150",
  //     totalPrice: "$170",
  //     includes: "includes taxes & fees",
  //   },
  //   reservationNote: "You will not be charged yet",
  //   images: ["/h10.jpg", "/h1.jpg", "/h2.jpg"],
  //   additionalDetails: {
  //     description: "Standard Room, 2 Single Beds, Garden View",
  //     highlights: [
  //       "Cozy atmosphere",
  //       "Air conditioning",
  //       "Free Wi-Fi",
  //       "Mini-fridge",
  //     ],
  //     view: "Garden view",
  //     amenities: [
  //       "Shampoo",
  //       "Slippers",
  //       "Toilet paper",
  //       "Towels",
  //       "Blackout curtains",
  //     ],
  //     entertainment: [
  //       "32-inch HDTV",
  //       "Premium TV channels",
  //     ],
  //     foodAndDrink: [
  //       "Complimentary breakfast",
  //       "Minibar",
  //     ],
  //     internet: "Wi-Fi",
  //     more: ["Housekeeping service"],
  //     accessibility: [
  //       "Elevator access",
  //       "Grab bars in bathroom",
  //     ],
  //     bathroom: [
  //       "Eco-friendly toiletries",
  //       "Shower only",
  //     ],
  //     guestLikes: [
  //       "Nice bed (55 reviews)",
  //       "Quiet (33 reviews)",
  //       "Clean bathroom (33 reviews)",
  //       "Spacious (67 reviews)",
  //       "Renovated, new (5 reviews)",
  //       "Clean (62 reviews)",
  //       "Great amenities (30 reviews)",
  //     ],
  //     ratingDetails: {
  //       overallRating: 8.3,
  //       reviews: 75,
  //       reviewText: "Very Good",
  //       guestLikes: [
  //         "Great location (40 reviews)",
  //         "Comfortable beds (20 reviews)",
  //         "Clean bathroom (30 reviews)",
  //       ],
  //     },
  //   },
  // },
  // {
  //   id: 5,
  //   title: "Executive Room, 1 King Bed",
  //   rating: 9.5,
  //   ratingText: "Exceptional",
  //   reviews: 200,
  //   sleeps: 2,
  //   bedType: "1 King Bed",
  //   refundPolicy: "Fully refundable",
  //   refundDate: "Before Thu, Dec 26",
  //   priceDetails: {
  //     discount: "$60 off",
  //     currentPrice: "$250",
  //     originalPrice: "$310",
  //     totalPrice: "$320",
  //     includes: "includes taxes & fees",
  //   },
  //   reservationNote: "You will not be charged yet",
  //   images: ["/h3.jpg", "/h4.jpg", "/h5.jpg"],
  //   additionalDetails: {
  //     description: "Executive Room, 1 King Bed, Mountain View",
  //     highlights: [
  //       "Luxury amenities",
  //       "Air conditioning",
  //       "Free Wi-Fi",
  //       "Coffee maker",
  //       "Refrigerator",
  //     ],
  //     view: "Mountain view",
  //     amenities: [
  //       "Free toiletries",
  //       "Hair dryer",
  //       "Private bathroom",
  //       "Shampoo",
  //       "Slippers",
  //       "Toilet paper",
  //       "Towels",
  //       "Blackout curtains",
  //     ],
  //     entertainment: [
  //       "55-inch HDTV",
  //       "On-demand movies",
  //       "Streaming services",
  //     ],
  //     foodAndDrink: [
  //       "Room service",
  //       "Coffee machine",
  //     ],
  //     internet: "Wi-Fi",
  //     more: ["Daily housekeeping"],
  //     accessibility: [
  //       "Wheelchair accessible",
  //       "Visual fire alarm",
  //     ],
  //     bathroom: [
  //       "Soaking bathtub",
  //       "Bathrobes",
  //       "Eco-friendly toiletries",
  //     ],
  //     guestLikes: [
  //       "Nice bed (55 reviews)",
  //       "Quiet (33 reviews)",
  //       "Clean bathroom (33 reviews)",
  //       "Spacious (67 reviews)",
  //       "Renovated, new (5 reviews)",
  //       "Clean (62 reviews)",
  //       "Great amenities (30 reviews)",
  //     ],
  //     ratingDetails: {
  //       overallRating: 9.7,
  //       reviews: 90,
  //       reviewText: "Exceptional",
  //       guestLikes: [
  //         "Stunning view (40 reviews)",
  //         "Comfy bed (60 reviews)",
  //       ],
  //     },
  //   },
  // },
  // {
  //   id: 6,
  //   title: "Deluxe Room, 1 Queen Bed",
  //   rating: 8.7,
  //   ratingText: "Very Good",
  //   reviews: 95,
  //   sleeps: 2,
  //   bedType: "1 Queen Bed",
  //   refundPolicy: "Fully refundable",
  //   refundDate: "Before Thu, Dec 29",
  //   priceDetails: {
  //     discount: "$40 off",
  //     currentPrice: "$180",
  //     originalPrice: "$220",
  //     totalPrice: "$210",
  //     includes: "includes taxes & fees",
  //   },
  //   reservationNote: "You will not be charged yet",
  //   images: ["/h6.jpg", "/h7.jpg", "/h8.jpg"],
  //   additionalDetails: {
  //     description: "Deluxe Room, 1 Queen Bed, City View",
  //     highlights: [
  //       "City view",
  //       "Air conditioning",
  //       "Free Wi-Fi",
  //       "Mini-fridge",
  //     ],
  //     view: "City view",
  //     amenities: [
  //       "Shampoo",
  //       "Hair dryer",
  //       "Private bathroom",
  //       "Toilet paper",
  //       "Towels",
  //     ],
  //     entertainment: [
  //       "32-inch HDTV",
  //       "Premium TV channels",
  //     ],
  //     foodAndDrink: [
  //       "Room service",
  //       "Minibar",
  //     ],
  //     internet: "Wi-Fi",
  //     more: ["Daily cleaning"],
  //     accessibility: [
  //       "Elevator access",
  //     ],
  //     bathroom: [
  //       "Eco-friendly toiletries",
  //       "Shower only",
  //     ],
  //     guestLikes: [
  //       "Nice bed (55 reviews)",
  //       "Quiet (33 reviews)",
  //       "Clean bathroom (33 reviews)",
  //       "Spacious (67 reviews)",
  //       "Renovated, new (5 reviews)",
  //       "Clean (62 reviews)",
  //       "Great amenities (30 reviews)",
  //     ],
  //     ratingDetails: {
  //       overallRating: 8.5,
  //       reviews: 80,
  //       reviewText: "Very Good",
  //       guestLikes: [
  //         "Great service (40 reviews)",
  //         "Clean and tidy (20 reviews)",
  //       ],
  //     },
  //   },
  // },
  // {
  //   id: 7,
  //   title: "Penthouse Suite, 1 King Bed",
  //   rating: 9.8,
  //   ratingText: "Exceptional",
  //   reviews: 230,
  //   sleeps: 3,
  //   bedType: "1 King Bed",
  //   refundPolicy: "Fully refundable",
  //   refundDate: "Before Mon, Jan 15",
  //   priceDetails: {
  //     discount: "$100 off",
  //     currentPrice: "$500",
  //     originalPrice: "$600",
  //     totalPrice: "$600",
  //     includes: "includes taxes & fees",
  //   },
  //   reservationNote: "You will not be charged yet",
  //   images: ["/h9.jpg", "/h10.jpg", "/h1.jpg"],
  //   additionalDetails: {
  //     description: "Penthouse Suite, 1 King Bed, City Skyline View",
  //     highlights: [
  //       "Private rooftop terrace",
  //       "Air conditioning",
  //       "Free Wi-Fi",
  //       "Jacuzzi",
  //       "Refrigerator",
  //     ],
  //     view: "City skyline view",
  //     amenities: [
  //       "Shampoo",
  //       "Slippers",
  //       "Toilet paper",
  //       "Towels",
  //       "Hair dryer",
  //     ],
  //     entertainment: [
  //       "75-inch HDTV",
  //       "On-demand movies",
  //       "Streaming services",
  //     ],
  //     foodAndDrink: [
  //       "In-room dining",
  //       "Minibar",
  //       "Private chef available",
  //     ],
  //     internet: "Wi-Fi",
  //     more: ["Personal concierge service"],
  //     accessibility: [
  //       "Wheelchair accessible",
  //     ],
  //     bathroom: [
  //       "Soaking tub",
  //       "Bathrobes",
  //       "Eco-friendly toiletries",
  //     ],
  //     guestLikes: [
  //       "Nice bed (55 reviews)",
  //       "Quiet (33 reviews)",
  //       "Clean bathroom (33 reviews)",
  //       "Spacious (67 reviews)",
  //       "Renovated, new (5 reviews)",
  //       "Clean (62 reviews)",
  //       "Great amenities (30 reviews)",
  //     ],
  //     ratingDetails: {
  //       overallRating: 9.9,
  //       reviews: 180,
  //       reviewText: "Exceptional",
  //       guestLikes: [
  //         "Incredible view (50 reviews)",
  //         "Luxurious amenities (70 reviews)",
  //       ],
  //     },
  //   },
  // },
  // {
  //   id: 8,
  //   title: "Luxury Suite, 1 King Bed",
  //   rating: 9.3,
  //   ratingText: "Excellent",
  //   reviews: 160,
  //   sleeps: 2,
  //   bedType: "1 King Bed",
  //   refundPolicy: "Fully refundable",
  //   refundDate: "Before Fri, Jan 10",
  //   priceDetails: {
  //     discount: "$90 off",
  //     currentPrice: "$350",
  //     originalPrice: "$440",
  //     totalPrice: "$400",
  //     includes: "includes taxes & fees",
  //   },
  //   reservationNote: "You will not be charged yet",
  //   images: ["/ca1.jpg", "/ca2.jpg", "/ca3.jpg"],
  //   additionalDetails: {
  //     description: "Luxury Suite, 1 King Bed, Garden View",
  //     highlights: [
  //       "Private balcony",
  //       "Air conditioning",
  //       "Free Wi-Fi",
  //       "Premium bedding",
  //     ],
  //     view: "Garden view",
  //     amenities: [
  //       "Hair dryer",
  //       "Private bathroom",
  //       "Shampoo",
  //       "Towels",
  //       "Slippers",
  //     ],
  //     entertainment: [
  //       "55-inch HDTV",
  //       "On-demand movies",
  //     ],
  //     foodAndDrink: [
  //       "Minibar",
  //       "Complimentary breakfast",
  //     ],
  //     internet: "Wi-Fi",
  //     more: ["Daily housekeeping"],
  //     accessibility: [
  //       "Elevator access",
  //       "Grab bars in bathroom",
  //     ],
  //     bathroom: [
  //       "Eco-friendly toiletries",
  //       "Shower only",
  //     ],
  //     guestLikes: [
  //       "Nice bed (55 reviews)",
  //       "Quiet (33 reviews)",
  //       "Clean bathroom (33 reviews)",
  //       "Spacious (67 reviews)",
  //       "Renovated, new (5 reviews)",
  //       "Clean (62 reviews)",
  //       "Great amenities (30 reviews)",
  //     ],
  //     ratingDetails: {
  //       overallRating: 9.4,
  //       reviews: 140,
  //       reviewText: "Wonderful",
  //       guestLikes: [
  //         "Peaceful atmosphere (50 reviews)",
  //         "Comfortable beds (50 reviews)",
  //       ],
  //     },
  //   },
  // },
  // {
  //   id: 9,
  //   title: "Oceanfront Suite, 1 King Bed",
  //   rating: 9.6,
  //   ratingText: "Exceptional",
  //   reviews: 190,
  //   sleeps: 2,
  //   bedType: "1 King Bed",
  //   refundPolicy: "Fully refundable",
  //   refundDate: "Before Tue, Jan 12",
  //   priceDetails: {
  //     discount: "$80 off",
  //     currentPrice: "$420",
  //     originalPrice: "$500",
  //     totalPrice: "$480",
  //     includes: "includes taxes & fees",
  //   },
  //   reservationNote: "You will not be charged yet",
  //   images: ["/ca4.jpg", "/ca5.jpg", "/ca6.jpg"],
  //   additionalDetails: {
  //     description: "Oceanfront Suite, 1 King Bed, Ocean View",
  //     highlights: [
  //       "Private deck with ocean view",
  //       "Air conditioning",
  //       "Free Wi-Fi",
  //       "Refrigerator",
  //     ],
  //     view: "Ocean view",
  //     amenities: [
  //       "Free toiletries",
  //       "Hair dryer",
  //       "Private bathroom",
  //       "Shampoo",
  //       "Towels",
  //     ],
  //     entertainment: [
  //       "60-inch HDTV",
  //       "On-demand movies",
  //       "Premium TV channels",
  //     ],
  //     foodAndDrink: [
  //       "Room service",
  //       "Minibar",
  //       "Complimentary breakfast",
  //     ],
  //     internet: "Wi-Fi",
  //     more: ["Daily cleaning"],
  //     accessibility: [
  //       "Wheelchair accessible",
  //     ],
  //     bathroom: [
  //       "Soaking tub",
  //       "Bathrobes",
  //       "Eco-friendly toiletries",
  //     ],
  //     guestLikes: [
  //       "Nice bed (55 reviews)",
  //       "Quiet (33 reviews)",
  //       "Clean bathroom (33 reviews)",
  //       "Spacious (67 reviews)",
  //       "Renovated, new (5 reviews)",
  //       "Clean (62 reviews)",
  //       "Great amenities (30 reviews)",
  //     ],
  //     ratingDetails: {
  //       overallRating: 9.7,
  //       reviews: 150,
  //       reviewText: "Exceptional",
  //       guestLikes: [
  //         "Stunning views (60 reviews)",
  //         "Spacious and clean (40 reviews)",
  //       ],
  //     },
  //   },
  // },
  // {
  //   id: 10,
  //   title: "Garden View Room, 2 Queen Beds",
  //   rating: 8.5,
  //   ratingText: "Very Good",
  //   reviews: 210,
  //   sleeps: 4,
  //   bedType: "2 Queen Beds",
  //   refundPolicy: "Fully refundable",
  //   refundDate: "Before Mon, Jan 5",
  //   priceDetails: {
  //     discount: "$30 off",
  //     currentPrice: "$160",
  //     originalPrice: "$190",
  //     totalPrice: "$190",
  //     includes: "includes taxes & fees",
  //   },
  //   reservationNote: "You will not be charged yet",
  //   images: ["/ca7.jpg", "/ca8.jpg", "/ca9.jpg"],
  //   additionalDetails: {
  //     description: "Garden View Room, 2 Queen Beds, Garden View",
  //     highlights: [
  //       "Comfortable and spacious",
  //       "Air conditioning",
  //       "Free Wi-Fi",
  //       "Mini-fridge",
  //     ],
  //     view: "Garden view",
  //     amenities: [
  //       "Shampoo",
  //       "Slippers",
  //       "Toilet paper",
  //       "Towels",
  //     ],
  //     entertainment: [
  //       "40-inch HDTV",
  //       "Cable TV channels",
  //     ],
  //     foodAndDrink: [
  //       "Complimentary breakfast",
  //       "In-room coffee maker",
  //     ],
  //     internet: "Wi-Fi",
  //     more: ["Housekeeping service"],
  //     accessibility: [
  //       "Elevator access",
  //       "Grab bars in bathroom",
  //     ],
  //     bathroom: [
  //       "Eco-friendly toiletries",
  //       "Shower only",
  //     ],
  //     guestLikes: [
  //       "Nice bed (55 reviews)",
  //       "Quiet (33 reviews)",
  //       "Clean bathroom (33 reviews)",
  //       "Spacious (67 reviews)",
  //       "Renovated, new (5 reviews)",
  //       "Clean (62 reviews)",
  //       "Great amenities (30 reviews)",
  //     ],
  //     ratingDetails: {
  //       overallRating: 8.6,
  //       reviews: 100,
  //       reviewText: "Good",
  //       guestLikes: [
  //         "Great location (40 reviews)",
  //         "Clean and tidy (30 reviews)",
  //       ],
  //     },
  //   },
  // },
  // {
  //   id: 11,
  //   title: "Luxury Penthouse, 2 King Beds",
  //   rating: 9.9,
  //   ratingText: "Exceptional",
  //   reviews: 260,
  //   sleeps: 4,
  //   bedType: "2 King Beds",
  //   refundPolicy: "Fully refundable",
  //   refundDate: "Before Wed, Jan 20",
  //   priceDetails: {
  //     discount: "$120 off",
  //     currentPrice: "$800",
  //     originalPrice: "$920",
  //     totalPrice: "$880",
  //     includes: "includes taxes & fees",
  //   },
  //   reservationNote: "You will not be charged yet",
  //   images: ["/ca10.jpg", "/ca11.jpg", "/h1.jpg"],
  //   additionalDetails: {
  //     description: "Luxury Penthouse, 2 King Beds, Ocean View",
  //     highlights: [
  //       "Private rooftop pool",
  //       "Air conditioning",
  //       "Free Wi-Fi",
  //       "Full kitchen",
  //     ],
  //     view: "Ocean view",
  //     amenities: [
  //       "Free toiletries",
  //       "Hair dryer",
  //       "Private bathroom",
  //       "Shampoo",
  //       "Slippers",
  //       "Towels",
  //     ],
  //     entertainment: [
  //       "100-inch HDTV",
  //       "On-demand movies",
  //       "Streaming services",
  //     ],
  //     foodAndDrink: [
  //       "Private chef",
  //       "In-room dining",
  //     ],
  //     internet: "Wi-Fi",
  //     more: ["Personal concierge service"],
  //     accessibility: [
  //       "Wheelchair accessible",
  //     ],
  //     bathroom: [
  //       "Soaking tub",
  //       "Bathrobes",
  //       "Eco-friendly toiletries",
  //     ],
  //     guestLikes: [
  //       "Nice bed (55 reviews)",
  //       "Quiet (33 reviews)",
  //       "Clean bathroom (33 reviews)",
  //       "Spacious (67 reviews)",
  //       "Renovated, new (5 reviews)",
  //       "Clean (62 reviews)",
  //       "Great amenities (30 reviews)",
  //     ],
  //     ratingDetails: {
  //       overallRating: 10.0,
  //       reviews: 230,
  //       reviewText: "Exceptional",
  //       guestLikes: [
  //         "Incredible rooftop pool (100 reviews)",
  //         "Spacious and luxurious (70 reviews)",
  //       ],
  //     },
  //   },
  // },
  // {
  //   id: 12,
  //   title: "Standard Room, 1 King Bed",
  //   rating: 8.3,
  //   ratingText: "Very Good",
  //   reviews: 150,
  //   sleeps: 2,
  //   bedType: "1 King Bed",
  //   refundPolicy: "Fully refundable",
  //   refundDate: "Before Fri, Jan 8",
  //   priceDetails: {
  //     discount: "$50 off",
  //     currentPrice: "$180",
  //     originalPrice: "$230",
  //     totalPrice: "$200",
  //     includes: "includes taxes & fees",
  //   },
  //   reservationNote: "You will not be charged yet",
  //   images: ["/h2.jpg", "/h3.jpg", "/h4.jpg"],
  //   additionalDetails: {
  //     description: "Standard Room, 1 King Bed, City View",
  //     highlights: [
  //       "Cozy and comfortable",
  //       "Air conditioning",
  //       "Free Wi-Fi",
  //       "Mini-fridge",
  //     ],
  //     view: "City view",
  //     amenities: [
  //       "Shampoo",
  //       "Hair dryer",
  //       "Private bathroom",
  //       "Toilet paper",
  //       "Towels",
  //     ],
  //     entertainment: [
  //       "40-inch HDTV",
  //       "Premium TV channels",
  //     ],
  //     foodAndDrink: [
  //       "Complimentary breakfast",
  //       "Minibar",
  //     ],
  //     internet: "Wi-Fi",
  //     more: ["Housekeeping service"],
  //     accessibility: [
  //       "Elevator access",
  //     ],
  //     bathroom: [
  //       "Eco-friendly toiletries",
  //       "Shower only",
  //     ],
  //     guestLikes: [
  //       "Nice bed (55 reviews)",
  //       "Quiet (33 reviews)",
  //       "Clean bathroom (33 reviews)",
  //       "Spacious (67 reviews)",
  //       "Renovated, new (5 reviews)",
  //       "Clean (62 reviews)",
  //       "Great amenities (30 reviews)",
  //     ],
  //     ratingDetails: {
  //       overallRating: 8.5,
  //       reviews: 130,
  //       reviewText: "Very Good",
  //       guestLikes: [
  //         "Comfortable room (50 reviews)",
  //         "Great location (40 reviews)",
  //       ],
  //     },
  //   },
  // },
  // {
  //   id: 13,
  //   title: "Executive Suite, 1 King Bed",
  //   rating: 9.2,
  //   ratingText: "Excellent",
  //   reviews: 180,
  //   sleeps: 2,
  //   bedType: "1 King Bed",
  //   refundPolicy: "Fully refundable",
  //   refundDate: "Before Thu, Jan 15",
  //   priceDetails: {
  //     discount: "$70 off",
  //     currentPrice: "$330",
  //     originalPrice: "$400",
  //     totalPrice: "$360",
  //     includes: "includes taxes & fees",
  //   },
  //   reservationNote: "You will not be charged yet",
  //   images: ["/h5.jpg", "/h6.jpg", "/h7.jpg"],
  //   additionalDetails: {
  //     description: "Executive Suite, 1 King Bed, City View",
  //     highlights: [
  //       "Spacious living area",
  //       "Air conditioning",
  //       "Free Wi-Fi",
  //       "Coffee maker",
  //     ],
  //     view: "City view",
  //     amenities: [
  //       "Free toiletries",
  //       "Hair dryer",
  //       "Private bathroom",
  //       "Shampoo",
  //       "Slippers",
  //       "Towels",
  //     ],
  //     entertainment: [
  //       "55-inch HDTV",
  //       "Streaming services",
  //     ],
  //     foodAndDrink: [
  //       "Room service",
  //       "Minibar",
  //     ],
  //     internet: "Wi-Fi",
  //     more: ["Daily cleaning"],
  //     accessibility: [
  //       "Wheelchair accessible",
  //     ],
  //     bathroom: [
  //       "Deep soaking tub",
  //       "Bathrobes",
  //       "Eco-friendly toiletries",
  //     ],
  //     guestLikes: [
  //       "Nice bed (55 reviews)",
  //       "Quiet (33 reviews)",
  //       "Clean bathroom (33 reviews)",
  //       "Spacious (67 reviews)",
  //       "Renovated, new (5 reviews)",
  //       "Clean (62 reviews)",
  //       "Great amenities (30 reviews)",
  //     ],
  //     ratingDetails: {
  //       overallRating: 9.4,
  //       reviews: 160,
  //       reviewText: "Wonderful",
  //       guestLikes: [
  //         "Spacious room (70 reviews)",
  //         "Great view (50 reviews)",
  //       ],
  //     },
  //   },
  // },
  // {
  //   id: 14,
  //   title: "Oceanview Studio, 1 Queen Bed",
  //   rating: 8.8,
  //   ratingText: "Very Good",
  //   reviews: 220,
  //   sleeps: 2,
  //   bedType: "1 Queen Bed",
  //   refundPolicy: "Fully refundable",
  //   refundDate: "Before Sun, Jan 10",
  //   priceDetails: {
  //     discount: "$40 off",
  //     currentPrice: "$160",
  //     originalPrice: "$200",
  //     totalPrice: "$180",
  //     includes: "includes taxes & fees",
  //   },
  //   reservationNote: "You will not be charged yet",
  //   images: ["/h8.jpg", "/h9.jpg", "/h10.jpg"],
  //   additionalDetails: {
  //     description: "Oceanview Studio, 1 Queen Bed, Ocean View",
  //     highlights: [
  //       "Panoramic ocean views",
  //       "Air conditioning",
  //       "Free Wi-Fi",
  //       "Kitchenette",
  //     ],
  //     view: "Ocean view",
  //     amenities: [
  //       "Free toiletries",
  //       "Hair dryer",
  //       "Private bathroom",
  //       "Shampoo",
  //       "Slippers",
  //       "Towels",
  //     ],
  //     entertainment: [
  //       "40-inch HDTV",
  //       "Cable TV channels",
  //     ],
  //     foodAndDrink: [
  //       "Complimentary breakfast",
  //       "In-room coffee maker",
  //     ],
  //     internet: "Wi-Fi",
  //     more: ["Daily cleaning"],
  //     accessibility: [
  //       "Wheelchair accessible",
  //     ],
  //     bathroom: [
  //       "Eco-friendly toiletries",
  //       "Shower only",
  //     ],
  //     guestLikes: [
  //       "Nice bed (55 reviews)",
  //       "Quiet (33 reviews)",
  //       "Clean bathroom (33 reviews)",
  //       "Spacious (67 reviews)",
  //       "Renovated, new (5 reviews)",
  //       "Clean (62 reviews)",
  //       "Great amenities (30 reviews)",
  //     ],
  //     ratingDetails: {
  //       overallRating: 8.9,
  //       reviews: 180,
  //       reviewText: "Good",
  //       guestLikes: [
  //         "Incredible view (90 reviews)",
  //         "Cozy room (50 reviews)",
  //       ],
  //     },
  //   },
  // },
  // {
  //   id: 15,
  //   title: "Mountain View Cabin, 1 King Bed",
  //   rating: 9.1,
  //   ratingText: "Excellent",
  //   reviews: 150,
  //   sleeps: 2,
  //   bedType: "1 King Bed",
  //   refundPolicy: "Fully refundable",
  //   refundDate: "Before Fri, Jan 8",
  //   priceDetails: {
  //     discount: "$70 off",
  //     currentPrice: "$260",
  //     originalPrice: "$330",
  //     totalPrice: "$290",
  //     includes: "includes taxes & fees",
  //   },
  //   reservationNote: "You will not be charged yet",
  //   images: ["/ca1.jpg", "/ca2.jpg", "/ca3.jpg"],
  //   additionalDetails: {
  //     description: "Mountain View Cabin, 1 King Bed, Mountain View",
  //     highlights: [
  //       "Secluded cabin with mountain view",
  //       "Air conditioning",
  //       "Free Wi-Fi",
  //       "Wood-burning fireplace",
  //     ],
  //     view: "Mountain view",
  //     amenities: [
  //       "Free toiletries",
  //       "Hair dryer",
  //       "Private bathroom",
  //       "Shampoo",
  //       "Slippers",
  //       "Towels",
  //     ],
  //     entertainment: [
  //       "45-inch HDTV",
  //       "Streaming services",
  //     ],
  //     foodAndDrink: [
  //       "Room service",
  //       "Coffee maker",
  //     ],
  //     internet: "Wi-Fi",
  //     more: ["Private balcony", "Pet-friendly"],
  //     accessibility: [
  //       "Wheelchair accessible",
  //     ],
  //     bathroom: [
  //       "Eco-friendly toiletries",
  //       "Walk-in shower",
  //     ],
  //     guestLikes: [
  //       "Nice bed (55 reviews)",
  //       "Quiet (33 reviews)",
  //       "Clean bathroom (33 reviews)",
  //       "Spacious (67 reviews)",
  //       "Renovated, new (5 reviews)",
  //       "Clean (62 reviews)",
  //       "Great amenities (30 reviews)",
  //     ],
  //     ratingDetails: {
  //       overallRating: 9.2,
  //       reviews: 130,
  //       reviewText: "Excellent",
  //       guestLikes: [
  //         "Private and peaceful (60 reviews)",
  //         "Amazing views (50 reviews)",
  //       ],
  //     },
  //   },
  // },
  // {
  //   id: 16,
  //   title: "Deluxe Suite, 1 King Bed, City View",
  //   rating: 9.4,
  //   ratingText: "Wonderful",
  //   reviews: 200,
  //   sleeps: 2,
  //   bedType: "1 King Bed",
  //   refundPolicy: "Fully refundable",
  //   refundDate: "Before Tue, Jan 12",
  //   priceDetails: {
  //     discount: "$100 off",
  //     currentPrice: "$500",
  //     originalPrice: "$600",
  //     totalPrice: "$550",
  //     includes: "includes taxes & fees",
  //   },
  //   reservationNote: "You will not be charged yet",
  //   images: ["/ca5.jpg", "/ca6.jpg", "/ca7.jpg"],
  //   additionalDetails: {
  //     description: "Deluxe Suite, 1 King Bed, City View",
  //     highlights: [
  //       "Panoramic city view",
  //       "Luxury amenities",
  //       "Free Wi-Fi",
  //       "Jacuzzi tub",
  //     ],
  //     view: "City view",
  //     amenities: [
  //       "Free toiletries",
  //       "Hair dryer",
  //       "Private bathroom",
  //       "Shampoo",
  //       "Slippers",
  //       "Towels",
  //     ],
  //     entertainment: [
  //       "60-inch HDTV",
  //       "On-demand movies",
  //     ],
  //     foodAndDrink: [
  //       "In-room dining",
  //       "Mini bar",
  //     ],
  //     internet: "Wi-Fi",
  //     more: ["Concierge service"],
  //     accessibility: [
  //       "Wheelchair accessible",
  //     ],
  //     bathroom: [
  //       "Jacuzzi tub",
  //       "Bathrobes",
  //       "Eco-friendly toiletries",
  //     ],
  //     guestLikes: [
  //       "Nice bed (55 reviews)",
  //       "Quiet (33 reviews)",
  //       "Clean bathroom (33 reviews)",
  //       "Spacious (67 reviews)",
  //       "Renovated, new (5 reviews)",
  //       "Clean (62 reviews)",
  //       "Great amenities (30 reviews)",
  //     ],
  //     ratingDetails: {
  //       overallRating: 9.5,
  //       reviews: 190,
  //       reviewText: "Exceptional",
  //       guestLikes: [
  //         "Amazing city view (80 reviews)",
  //         "Jacuzzi experience (70 reviews)",
  //       ],
  //     },
  //   },
  // },
  // {
  //   id: 17,
  //   title: "Beachfront Villa, 3 Queen Beds",
  //   rating: 9.7,
  //   ratingText: "Exceptional",
  //   reviews: 250,
  //   sleeps: 6,
  //   bedType: "3 Queen Beds",
  //   refundPolicy: "Fully refundable",
  //   refundDate: "Before Sat, Jan 16",
  //   priceDetails: {
  //     discount: "$150 off",
  //     currentPrice: "$850",
  //     originalPrice: "$1000",
  //     totalPrice: "$900",
  //     includes: "includes taxes & fees",
  //   },
  //   reservationNote: "You will not be charged yet",
  //   images: ["/ca8.jpg", "/ca9.jpg", "/ca10.jpg"],
  //   additionalDetails: {
  //     description: "Beachfront Villa, 3 Queen Beds, Ocean View",
  //     highlights: [
  //       "Private beachfront",
  //       "Air conditioning",
  //       "Free Wi-Fi",
  //       "Fully equipped kitchen",
  //     ],
  //     view: "Ocean view",
  //     amenities: [
  //       "Free toiletries",
  //       "Hair dryer",
  //       "Private bathroom",
  //       "Shampoo",
  //       "Slippers",
  //       "Towels",
  //     ],
  //     entertainment: [
  //       "70-inch HDTV",
  //       "Premium movie channels",
  //     ],
  //     foodAndDrink: [
  //       "In-room dining",
  //       "Barbecue facilities",
  //     ],
  //     internet: "Wi-Fi",
  //     more: ["Private pool", "24-hour room service"],
  //     accessibility: [
  //       "Wheelchair accessible",
  //     ],
  //     bathroom: [
  //       "Deep soaking tub",
  //       "Bathrobes",
  //       "Eco-friendly toiletries",
  //     ],
  //     guestLikes: [
  //       "Nice bed (55 reviews)",
  //       "Quiet (33 reviews)",
  //       "Clean bathroom (33 reviews)",
  //       "Spacious (67 reviews)",
  //       "Renovated, new (5 reviews)",
  //       "Clean (62 reviews)",
  //       "Great amenities (30 reviews)",
  //     ],
  //     ratingDetails: {
  //       overallRating: 9.8,
  //       reviews: 240,
  //       reviewText: "Exceptional",
  //       guestLikes: [
  //         "Stunning beachfront location (100 reviews)",
  //         "Luxury amenities (80 reviews)",
  //       ],
  //     },
  //   },
  // },
];
