export const  attractionAds = [
    {
      id: 1,
      imageUrl: "/h1.jpg",
      title: "The High Roller Observation Wheel Tickets",
      distance: "0.3 mi away",
      rating: "8.8/10",
      reviews: "(5,762)",
      originalPrice: "$20",
      currentPrice: "$20",
      priceDetails: {
        originalPrice: "$20",
        currentPrice: "$20",
        perAdult: "per adult",
      },
      description: "The High Roller Observation Wheel Tickets",
    },
    {
      id: 2,
      imageUrl: "/h2.jpg",
      title: "Las Vegas Hop-On Hop-Off Open-Top Big Bus Tour",
      distance: "0.1 mi away",
      rating: "7.6/10",
      reviews: "(620)",
      originalPrice: "$55",
      currentPrice: "$50",
      priceDetails: {
        originalPrice: "$55",
        currentPrice: "$50",
        perAdult: "per adult",
      },
      description: "Las Vegas Hop-On Hop-Off Open-Top Big Bus Tour",
    },
    {
      id: 3,
      imageUrl: "/h3.jpg",
      title: "Fly LINQ Zipline",
      distance: "0.3 mi away",
      rating: "7.6/10",
      reviews: "(510)",
      originalPrice: "$46",
      currentPrice: "$46",
      priceDetails: {
        originalPrice: "$46",
        currentPrice: "$46",
        perAdult: "per adult",
      },
      description: "Fly LINQ Zipline",
    },
    {
      id: 4,
      imageUrl: "/h4.jpg",
      title: "VEGAS! THE SHOW",
      distance: "0.8 mi away",
      rating: "9.2/10",
      reviews: "(875)",
      originalPrice: "$70",
      currentPrice: "$70",
      priceDetails: {
        originalPrice: "$70",
        currentPrice: "$70",
        perAdult: "per traveler",
      },
      description: "VEGAS! THE SHOW",
    },
    {
      id: 5,
      imageUrl: "/h5.jpg",
      title: "Las Vegas Eiffel Tower Viewing Deck Tickets",
      distance: "0.7 mi away",
      rating: "7.8/10",
      reviews: "(1,065)",
      originalPrice: "$32",
      currentPrice: "$32",
      priceDetails: {
        originalPrice: "$32",
        currentPrice: "$32",
        perAdult: "per adult",
      },
      description: "Las Vegas Eiffel Tower Viewing Deck Tickets",
    },
    {
      id: 6,
      imageUrl: "/h6.jpg",
      title: "Grand Canyon National Park South Rim Bus Tour with Professional Tour Guide",
      distance: "Varies",
      rating: "N/A",
      reviews: "N/A",
      originalPrice: "N/A",
      currentPrice: "Varies",
      priceDetails: {
        originalPrice: "N/A",
        currentPrice: "Varies",
        perAdult: "Varies",
      },
      description: "Grand Canyon National Park South Rim Bus Tour with Professional Tour Guide",
    },
  ];
  