const roomData = [
    {
      id: 1,
      title: "Luxury Room, 1 King Bed",
      rating: 9.2,
      ratingText: "Wonderful",
      reviews: 197,
      sleeps: 4,
      bedType: "1 King Bed",
      refundPolicy: "Fully refundable",
      refundDate: "Before Sun, Dec 15",
      priceDetails: {
        discount: "$42 off",
        currentPrice: "$170",
        originalPrice: "$212",
        totalPrice: "$249",
        includes: "includes taxes & fees",
      },
      reservationNote: "You will not be charged yet",
      images: ["/h1.jpg", "/h2.jpg", "/h3.jpg"],
    },
    {
      id: 2,
      title: "Deluxe Room, 2 Queen Beds",
      rating: 8.5,
      ratingText: "Very Good",
      reviews: 150,
      sleeps: 6,
      bedType: "2 Queen Beds",
      refundPolicy: "Fully refundable",
      refundDate: "Before Fri, Dec 20",
      priceDetails: {
        discount: "$30 off",
        currentPrice: "$180",
        originalPrice: "$210",
        totalPrice: "$240",
        includes: "includes taxes & fees",
      },
      reservationNote: "You will not be charged yet",
      images: ["/h4.jpg", "/h5.jpg", "/h6.jpg"],
    },
    {
      id: 3,
      title: "Superior Room, 1 Queen Bed",
      rating: 7.9,
      ratingText: "Good",
      reviews: 120,
      sleeps: 2,
      bedType: "1 Queen Bed",
      refundPolicy: "Non-refundable",
      refundDate: "No refund available",
      priceDetails: {
        discount: "$20 off",
        currentPrice: "$130",
        originalPrice: "$150",
        totalPrice: "$170",
        includes: "includes taxes & fees",
      },
      reservationNote: "You will not be charged yet",
      images: ["/h7.jpg", "/h8.jpg", "/h9.jpg"],
    },
    {
      id: 4,
      title: "Family Room, 2 Double Beds",
      rating: 8.8,
      ratingText: "Very Good",
      reviews: 140,
      sleeps: 5,
      bedType: "2 Double Beds",
      refundPolicy: "Fully refundable",
      refundDate: "Before Tue, Dec 17",
      drinks: [
        {welDrink: "Free welcome drink"},
        {welDrink: "Drinks and hors d'oeuvres"}
      ],
      priceDetails: {
        discount: "$50 off",
        currentPrice: "$200",
        originalPrice: "$250",
        totalPrice: "$275",
        includes: "includes taxes & fees",
      },
      reservationNote: "You will not be charged yet",
      images: ["/h10.jpg", "/h1.jpg", "/h2.jpg"],
    },
    {
      id: 5,
      title: "Penthouse Suite, 1 King Bed",
      rating: 9.8,
      ratingText: "Excellent",
      reviews: 300,
      sleeps: 2,
      bedType: "1 King Bed",
      refundPolicy: "Fully refundable",
      refundDate: "Before Thu, Dec 19",
      priceDetails: {
        discount: "$100 off",
        currentPrice: "$350",
        originalPrice: "$450",
        totalPrice: "$500",
        includes: "includes taxes & fees",
      },
      reservationNote: "You will not be charged yet",
      images: ["/h3.jpg", "/h4.jpg", "/h5.jpg"],
    },
    {
      id: 6,
      title: "Standard Room, 1 King Bed",
      rating: 8.2,
      ratingText: "Very Good",
      reviews: 180,
      sleeps: 2,
      bedType: "1 King Bed",
      refundPolicy: "Fully refundable",
      refundDate: "Before Wed, Dec 18",
      priceDetails: {
        discount: "$25 off",
        currentPrice: "$150",
        originalPrice: "$175",
        totalPrice: "$200",
        includes: "includes taxes & fees",
      },
      reservationNote: "You will not be charged yet",
      images: ["/h6.jpg", "/h7.jpg", "/h8.jpg"],
    },
    {
      id: 7,
      title: "Luxury Suite, 2 Queen Beds",
      rating: 9.4,
      ratingText: "Superb",
      reviews: 230,
      sleeps: 6,
      bedType: "2 Queen Beds",
      refundPolicy: "Fully refundable",
      refundDate: "Before Mon, Dec 16",
      priceDetails: {
        discount: "$60 off",
        currentPrice: "$220",
        originalPrice: "$280",
        totalPrice: "$310",
        includes: "includes taxes & fees",
      },
      reservationNote: "You will not be charged yet",
      images: ["/h9.jpg", "/h10.jpg", "/ca1.jpg"],
    },
    {
      id: 8,
      title: "Junior Suite, 1 Queen Bed",
      rating: 8.6,
      ratingText: "Very Good",
      reviews: 110,
      sleeps: 2,
      bedType: "1 Queen Bed",
      refundPolicy: "Fully refundable",
      refundDate: "Before Fri, Dec 20",
      priceDetails: {
        discount: "$40 off",
        currentPrice: "$170",
        originalPrice: "$210",
        totalPrice: "$250",
        includes: "includes taxes & fees",
      },
      reservationNote: "You will not be charged yet",
      images: ["/ca2.jpg", "/ca3.jpg", "/ca4.jpg"],
    },
    {
      id: 9,
      title: "Ocean View Room, 2 Double Beds",
      rating: 8.9,
      ratingText: "Very Good",
      reviews: 160,
      sleeps: 5,
      bedType: "2 Double Beds",
      refundPolicy: "Fully refundable",
      refundDate: "Before Thu, Dec 19",
      priceDetails: {
        discount: "$55 off",
        currentPrice: "$215",
        originalPrice: "$270",
        totalPrice: "$290",
        includes: "includes taxes & fees",
      },
      reservationNote: "You will not be charged yet",
      images: ["/ca5.jpg", "/ca6.jpg", "/ca7.jpg"],
    },
    {
      id: 10,
      title: "Oceanfront Suite, 1 King Bed",
      rating: 9.5,
      ratingText: "Excellent",
      reviews: 250,
      sleeps: 2,
      bedType: "1 King Bed",
      refundPolicy: "Fully refundable",
      refundDate: "Before Tue, Dec 17",
      priceDetails: {
        discount: "$90 off",
        currentPrice: "$350",
        originalPrice: "$440",
        totalPrice: "$490",
        includes: "includes taxes & fees",
      },
      reservationNote: "You will not be charged yet",
      images: ["/ca8.jpg", "/ca9.jpg", "/ca10.jpg"],
    },
    {
      id: 11,
      title: "Mountain View Room, 2 Queen Beds",
      rating: 7.8,
      ratingText: "Good",
      reviews: 80,
      sleeps: 6,
      bedType: "2 Queen Beds",
      refundPolicy: "Fully refundable",
      refundDate: "Before Wed, Dec 18",
      priceDetails: {
        discount: "$30 off",
        currentPrice: "$160",
        originalPrice: "$190",
        totalPrice: "$220",
        includes: "includes taxes & fees",
      },
      reservationNote: "You will not be charged yet",
      images: ["/ca11.jpg", "/ca1.jpg", "/ca2.jpg"],
    },
    {
      id: 12,
      title: "City View Suite, 1 King Bed",
      rating: 9.1,
      ratingText: "Wonderful",
      reviews: 210,
      sleeps: 2,
      bedType: "1 King Bed",
      refundPolicy: "Fully refundable",
      refundDate: "Before Fri, Dec 20",
      priceDetails: {
        discount: "$50 off",
        currentPrice: "$220",
        originalPrice: "$270",
        totalPrice: "$310",
        includes: "includes taxes & fees",
      },
      reservationNote: "You will not be charged yet",
      images: ["/ca3.jpg", "/ca4.jpg", "/ca5.jpg"],
    },
    {
      id: 13,
      title: "Garden Room, 2 Double Beds",
      rating: 8.3,
      ratingText: "Very Good",
      reviews: 100,
      sleeps: 5,
      bedType: "2 Double Beds",
      refundPolicy: "Fully refundable",
      refundDate: "Before Mon, Dec 16",
      priceDetails: {
        discount: "$35 off",
        currentPrice: "$180",
        originalPrice: "$215",
        totalPrice: "$240",
        includes: "includes taxes & fees",
      },
      reservationNote: "You will not be charged yet",
      images: ["/ca6.jpg", "/ca7.jpg", "/ca8.jpg"],
    },
    {
      id: 14,
      title: "Premium Room, 1 Queen Bed",
      rating: 9.0,
      ratingText: "Excellent",
      reviews: 190,
      sleeps: 2,
      bedType: "1 Queen Bed",
      refundPolicy: "Fully refundable",
      refundDate: "Before Thu, Dec 19",
      priceDetails: {
        discount: "$40 off",
        currentPrice: "$180",
        originalPrice: "$220",
        totalPrice: "$260",
        includes: "includes taxes & fees",
      },
      reservationNote: "You will not be charged yet",
      images: ["/ca9.jpg", "/ca10.jpg", "/ca11.jpg"],
    },
    {
      id: 15,
      title: "Executive Suite, 2 Queen Beds",
      rating: 9.3,
      ratingText: "Superb",
      reviews: 240,
      sleeps: 6,
      bedType: "2 Queen Beds",
      refundPolicy: "Fully refundable",
      refundDate: "Before Sun, Dec 15",
      priceDetails: {
        discount: "$75 off",
        currentPrice: "$260",
        originalPrice: "$335",
        totalPrice: "$400",
        includes: "includes taxes & fees",
      },
      reservationNote: "You will not be charged yet",
      images: ["/h1.jpg", "/ca1.jpg", "/h2.jpg"],
    },
    {
      id: 16,
      title: "Skyview Room, 1 King Bed",
      rating: 9.6,
      ratingText: "Excellent",
      reviews: 280,
      sleeps: 2,
      bedType: "1 King Bed",
      refundPolicy: "Fully refundable",
      refundDate: "Before Mon, Dec 16",
      priceDetails: {
        discount: "$85 off",
        currentPrice: "$270",
        originalPrice: "$355",
        totalPrice: "$420",
        includes: "includes taxes & fees",
      },
      reservationNote: "You will not be charged yet",
      images: ["/h2.jpg", "/h3.jpg", "/ca6.jpg"],
    }
  ];
  
  export default roomData;
  