export const roomAds = [
  {
    id: 1,
    title: "Marriott's Grand Chateau (No Resort Fee)",
    location: "Las Vegas",
    features: ["Pool", "Free WiFi", "Restaurant", "Air conditioning"],
    rating: 9.4,
    ratingText: "Exceptional",
    reviews: 3091,
    priceDetails: {
      currentPrice: "$299",
      originalPrice: "$399",
      perNight: "per night",
      totalPrice: "$339 total",
      includes: "includes taxes & fees",
    },
    reservationNote: "Outdoor pool, open 10:00 AM to 6:00 PM, cabanas (surcharge)",
    images: ["/h1.jpg", "/h2.jpg", "/h3.jpg"],
  },
  {
    id: 2,
    title: "Westgate Las Vegas Resort & Casino",
    location: "Las Vegas",
    features: ["Pool", "Hot Tub", "Spa", "Pet friendly"],
    rating: 8.0,
    ratingText: "Very Good",
    reviews: 3873,
    priceDetails: {
      discount: "The price was $53",
      currentPrice: "$42",
      originalPrice: "$142",
      perNight: "per night",
      totalPrice: "$99 total",
      includes: "includes taxes & fees",
    },
    reservationNote: "Ad - Exterior",
    images: ["/h4.jpg", "/h5.jpg", "/h6.jpg"],
  },
  {
    id: 3,
    title: "TownePlace Suites By Marriott Las Vegas Stadium District",
    location: "Las Vegas",
    features: ["Pool", "Breakfast included", "Pet friendly", "Free WiFi"],
    rating: 9.2,
    ratingText: "Wonderful",
    reviews: 288,
    priceDetails: {
      currentPrice: "$143",
      originalPrice: "$243",
      perNight: "per night",
      totalPrice: "$162 total",
      includes: "includes taxes & fees",
    },
    reservationNote: "Ad",
    images: ["/h7.jpg", "/h8.jpg", "/h9.jpg"],
  },
  {
    id: 4,
    title: "The Venetian Resort Las Vegas",
    location: "Las Vegas",
    features: ["Free airport shuttle", "Pool", "Spa", "Free parking"],
    rating: 9.1,
    ratingText: "Wonderful",
    reviews: 4050,
    priceDetails: {
      currentPrice: "$249",
      perNight: "per night",
      totalPrice: "$289 total",
      includes: "includes taxes & fees",
    },
    reservationNote: "Luxury suites and premium services",
    images: ["/h10.jpg", "/h1.jpg", "/h2.jpg"],
  },
  {
    id: 5,
    title: "Bellagio Hotel & Casino",
    location: "Las Vegas",
    features: ["Pool", "Spa", "Fine dining", "Air conditioning"],
    rating: 9.5,
    ratingText: "Exceptional",
    reviews: 5000,
    priceDetails: {
      discount: "The price was $450",
      currentPrice: "$350",
      perNight: "per night",
      totalPrice: "$390 total",
      includes: "includes taxes & fees",
    },
    reservationNote: "Experience the iconic fountains",
    images: ["/h3.jpg", "/h4.jpg", "/h5.jpg"],
  },
  {
    id: 6,
    title: "MGM Grand Hotel & Casino",
    location: "Las Vegas",
    features: ["Casino", "Pool", "Nightclub", "Free parking"],
    rating: 8.8,
    ratingText: "Very Good",
    reviews: 3200,
    priceDetails: {
      discount: "The price was $175",
      currentPrice: "$150",
      originalPrice: "$250",
      perNight: "per night",
      totalPrice: "$190 total",
      includes: "includes taxes & fees",
    },
    reservationNote: "Vibrant nightlife and entertainment",
    images: ["/h6.jpg", "/h7.jpg", "/h8.jpg"],
  },
  {
    id: 7,
    title: "Caesars Palace",
    location: "Las Vegas",
    features: ["Pool", "Casino", "Luxury Spa", "Fitness Center"],
    rating: 9.0,
    ratingText: "Excellent",
    reviews: 4700,
    priceDetails: {
      discount: "The price was $280",
      currentPrice: "$220",
      perNight: "per night",
      totalPrice: "$260 total",
      includes: "includes taxes & fees",
    },
    reservationNote: "Iconic Roman-themed luxury",
    images: ["/h9.jpg", "/h10.jpg", "/ca1.jpg"],
  },
  {
    id: 8,
    title: "Aria Resort & Casino",
    location: "Las Vegas",
    features: ["Casino", "Pool", "Fine dining", "Fitness Center"],
    rating: 9.3,
    ratingText: "Wonderful",
    reviews: 3000,
    priceDetails: {
      discount: "The price was $250",
      currentPrice: "$210",
      originalPrice: "$310",
      perNight: "per night",
      totalPrice: "$260 total",
      includes: "includes taxes & fees",
    },
    reservationNote: "Eco-friendly luxury in the heart of the Strip",
    images: ["/ca2.jpg", "/ca3.jpg", "/ca4.jpg"],
  },
  {
    id: 9,
    title: "Luxor Hotel & Casino",
    location: "Las Vegas",
    features: ["Casino", "Pool", "Pet friendly", "Free parking"],
    rating: 8.2,
    ratingText: "Very Good",
    reviews: 2300,
    priceDetails: {
      discount: "The price was $180",
      currentPrice: "$150",
      perNight: "per night",
      totalPrice: "$200 total",
      includes: "includes taxes & fees",
    },
    reservationNote: "Unique pyramid design and amenities",
    images: ["/ca5.jpg", "/ca6.jpg", "/ca7.jpg"],
  },
];
